# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gatsby Build

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20'
      - run: npm ci
      - name: Build Gatsby Site
        env:
          NODE_ENV: production
          DB_SERVER_ADDRESS: ${{ secrets.DB_SERVER_ADDRESS }}
          DB_SERVER_PORT: ${{ secrets.DB_SERVER_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        # This will run the build script defined in package.json
        run: npm run build --if-present